### PR TITLE
Fix error in type of memory.init introduced in #56

### PR DESCRIPTION
**Pull request by sbc100**
Sorry for the churn.  This time I'll double check the test in wabt before updating the testsuite repo.

### CODE REVIEW

**Comment by dschuff** [comment]
Should the size and offset fields of memory.init not be the same size as pointers, a la `size_t`?

**Comment by sbc100** [comment]
Those arguments are supposed to stay as i32.. at least according the overview and current implementations.

**Comment by bvisness** [comment]
I think it makes sense for these parameters to remain i32 since they are determined by the data segment, which still doesn't use 64-bit indices. (Nor should it, probably.)

**Comment by dschuff** [comment]
Ah, right. I guess that logic would make more sense for memory.copy than memory.init.

**Pull request merged**
