### PR TITLE
Test largest valid initial and max size for memory64 in memory64.wast

### PR DESCRIPTION
**Pull request by evicy**

### CODE REVIEW

**Review by sbc100 — APPROVED** [review]
Thanks for working on this!

**Comment by bvisness** [comment]
Does this really actually work? Similar to my comment [here](https://github.com/WebAssembly/memory64/pull/104#issuecomment-2474399913), I don't think it's wise to actually try allocating memories with the largest possible initial size. (That said, we clearly were missing the test for the largest possible maximum size.)

**Comment by sbc100** [comment]
Ah I was assuming this was just check that the module validates, but if its really trying to allocate a memory with 0x1_0000_0000_0000 pages that seems unlikely to work in any environment.

**Comment by bvisness** [comment]
We could use the new `module definition` form that only defines but does not instantiate the module. Regardless, since `(module foo)` generally does instantiate the module (per the [interpreter readme](https://github.com/WebAssembly/memory64/tree/main/interpreter#scripts)) I think we clearly shouldn't naively do this, #104, or #105.

I can almost guarantee that most spec test runners in wasm runtimes would explode on these tests as written. Why the spec interpreter _doesn't_ fail on this one is a mystery to me.

**Comment by rossberg** [comment]
Right, I think `module definition` is what you want for these. In addition to definitions, it's also worth testing the validity of large bounds on imports. Again, with `module definition` you can test this without actually needing suitable imports to link with.

**Comment by backes** [comment]
Agreed, let's switch the first added line to `module definition`. The second added line should be fine.

**Comment by evicy** [comment]
Thanks for noting this! I didn't realize that this also instantiates the module.
Just to note, [PR 108](https://github.com/WebAssembly/memory64/pull/108) fixed this.

**Pull request merged**
